### PR TITLE
Allow Wayland

### PR DESCRIPTION
**Pull request by lionirdeadman**
Happy to see this though, Wayland should be added :wink:

### CODE REVIEW

**Comment by x80486** [comment]
I'll go ahead and add it...but last time I checked Electron didn't have Wayland support.

I'll try to see if I can get this done today so I can sent it to Flathub. Right now I'm facing a weird issue with `npm` (again :anger:) and some spellchecker – I know @gasinvein might know how to solve this :sweat_smile:

**Comment by gasinvein** [comment]
> weird issue with npm (again ￼)

Just throw `npm` away and use `yarn`.

**Comment by x80486** [comment]
> 
> Just throw `npm` away and use `yarn`.

@gasinvein, I'm in the process of migrating this to `YARN` to see if I can make it work, but I don't see any guides in `flatpak-builder-tools` on how to use it.

I'm trying to automate the process of generating the `generated-sources.json` files that I would need, but these commands that I have in `flatpak_build.sh` only generate empty file(s):

```shell
python3 ../flatpak-yarn-generator.py package-lock.json -o ../generated-sources.json
python3 ../flatpak-yarn-generator.py app/package-lock.json -o ../generated-sources-app.json
```

Do you recap how did you go about generating `yarn.lock` and `generated-sources.json` using the `flatpak-yarn-generator.py` Python script provided by `flatpak-builder-tools`?

**Comment by gasinvein** [comment]
@x80486  You need to generate `yarn.lock` yourself with yarn. Run `yarn install` locally, outside flatpak-builder, and put generated lockfile into flatpak-builder sources.

**Comment by x80486** [comment]
All right...thanks for the tip. By running `bootstrap.sh` I'm able to generate `generated-sources[-app].json` and `yarn.lock` (I guess successfully)...but, of course, now I got into another hurdle with Node.js that I haven't seen before :sob: 

```shell
x80486@ubuntu-vm:~/Workshop/flathub$ flatpak-builder build --force-clean --install-deps-from=flathub --install --user org.standardnotes.standardnotes.json
Dependency Sdk: org.freedesktop.Sdk 18.08
Looking for updates…
Nothing to do.
Dependency Runtime: org.freedesktop.Platform 18.08
Looking for updates…
Nothing to do.
Dependency Base: io.atom.electron.BaseApp 18.08
Looking for updates…
Nothing to do.
Emptying app dir 'build'
Downloading sources
Downloading https://nodejs.org/dist/v10.15.3/node-v10.15.3.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.3M  100 19.3M    0     0  12.4M      0  0:00:01  0:00:01 --:--:-- 12.4M
Starting build of org.standardnotes.standardnotes
Cache miss, checking out last cache hit
========================================================================
Building module nodejs in /home/x80486/Workshop/flathub/.flatpak-builder/build/nodejs-2
========================================================================
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
'import sitecustomize' failed; use -v for traceback
creating icu_config.gypi
* Using ICU in deps/icu-small
WARNING: Using floating patch "tools/icu/patches/62/source/i18n/decimfmt.cpp" from "tools/icu"
creating icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': [],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'asan': 0,
                 'build_v8_with_gn': 'false',
                 'coverage': 'false',
                 'debug_nghttp2': 'false',
                 'enable_lto': 'false',
                 'enable_pgo_generate': 'false',
                 'enable_pgo_use': 'false',
                 'force_dynamic_crt': 0,
                 'gas_version': '2.31',
                 'host_arch': 'x64',
                 'icu_data_in': '../../deps/icu-small/source/data/in/icudt62l.dat',
                 'icu_endianness': 'l',
                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                 'icu_locales': 'en,root',
                 'icu_path': 'deps/icu-small',
                 'icu_small': 'true',
                 'icu_ver_major': '62',
                 'llvm_version': 0,
                 'node_byteorder': 'little',
                 'node_debug_lib': 'false',
                 'node_enable_d8': 'false',
                 'node_enable_v8_vtunejit': 'false',
                 'node_install_npm': 'true',
                 'node_module_version': 64,
                 'node_no_browser_globals': 'false',
                 'node_prefix': '/app',
                 'node_release_urlbase': '',
                 'node_shared': 'false',
                 'node_shared_cares': 'false',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_nghttp2': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_target_type': 'executable',
                 'node_use_bundled_v8': 'true',
                 'node_use_dtrace': 'false',
                 'node_use_etw': 'false',
                 'node_use_large_pages': 'false',
                 'node_use_openssl': 'true',
                 'node_use_pch': 'false',
                 'node_use_perfctr': 'false',
                 'node_use_v8_platform': 'true',
                 'node_with_ltcg': 'false',
                 'node_without_node_options': 'false',
                 'openssl_fips': '',
                 'openssl_no_asm': 0,
                 'shlib_suffix': 'so.64',
                 'target_arch': 'x64',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 1,
                 'v8_enable_inspector': 1,
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_promise_internal_field_count': 1,
                 'v8_random_seed': 0,
                 'v8_trace_maps': 0,
                 'v8_typed_array_max_size_in_heap': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 0}}
creating config.gypi
creating config.status
creating config.mk
running: 
    python tools/gyp_node.py --no-parallel -f make-linux
'import sitecustomize' failed; use -v for traceback
gyp: Call to 'python -c "import sys; print sys.byteorder"' returned exit status 0 while in /run/build/nodejs/deps/v8/gypfiles/v8.gyp. while loading dependencies of /run/build/nodejs/node.gyp while trying to load /run/build/nodejs/node.gyp
Error running GYP
Error: module nodejs: Child process exited with code 1
```

I'll see what I can do :man_shrugging:

**Comment by gasinvein** [comment]
@x80486 No idea what it is. Since it's `nodejs` module failing, it's probably not related to npm/yarn.
Also this discussion is kinda off-topic here.

**Comment by x80486** [comment]
No that's great...thanks for the help! Something is fishy here since `OpenDrive` is also failing with the same error in `master`, and that built successfully a while back.

@lionirdeadman, I'll create another repository with the correct ID for this application; I'll add the `wayland` support also on that one. Thanks for the PR!

**Pull request merged**
